#!/bin/sh
#DEBHELPER#
if [ -d /opt/makoureactor ];then
 rm -r /opt/makoureactor
fi
if [ -f /usr/share/makoureactor/makoureactor ];then
 rm /usr/share/makoureactor/makoureactor
fi
if [ -f /usr/share/makoureactor/vars.cfg ];then
 rm /usr/share/makoureactor/vars.cfg
fi
